name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Start SSH Server in WSL
      run: sudo service ssh start

    - name: Ensure deployment directory exists
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
        chmod 600 private_key
        ssh -i private_key srikanth@localhost 'mkdir -p /home/srikanth/action-runners/deploy'

    - name: Deploy to Localhost
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
        chmod 600 private_key
        scp -i private_key -r ./publish/* srikanth@localhost:/home/srikanth/action-runners/deploy/
        ssh -i private_key srikanth@localhost 'sudo systemctl restart your-app-service'
        rm private_key
